function CapGaugeOutput = CapGauge3Import(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  WAVETRIAL1RUN110HZ = IMPORTFILE3(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  WAVETRIAL1RUN110HZ = IMPORTFILE3(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  WaveTrial1Run110Hz = CapGauge3Import("F:\Thesis\Wave Tank Tests\Wave Gauge Tests\Capacitance Gauges\WaveTrial1_Run1_10Hz.txt", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Oct-2023 16:15:11

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 34);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time", "Value", "Peak", "Offset", "Gauge", "Value1", "Peak1", "Offset1", "Gauge1", "Value2", "Peak2", "Offset2", "Gauge2", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34"];
opts.SelectedVariableNames = ["Time", "Value", "Peak", "Offset", "Gauge", "Value1", "Peak1", "Offset1", "Gauge1", "Value2", "Peak2", "Offset2", "Gauge2"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Time", "InputFormat", "HH:mm:ss.SSS");

% Import the data
CapGaugeOutput = readtable(filename, opts);

end