function VerticalVelocity = importdat2(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  VERTICALVELOCITY = IMPORTFILE3(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  VERTICALVELOCITY = IMPORTFILE3(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  VerticalVelocities = importdat("D:\Thesis\Scaled Simulations\Morison Coefficients\13\Vertical Velocity.txt", [15, 5963]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Sep-2023 12:47:53

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [15, 5963];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["x", "y", "z", "w", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13"];
opts.SelectedVariableNames = ["x", "y", "z", "w"];
opts.VariableTypes = ["double", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "x", "TrimNonNumeric", true);
opts = setvaropts(opts, "x", "ThousandsSeparator", ",");

% Import the data
VerticalVelocity = readtable(filename, opts);

end