function Reference1301Pressure = importpress(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  REFERENCE1301PRESSURE = IMPORTFILE2(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  REFERENCE1301PRESSURE = IMPORTFILE2(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Reference1301Pressure = importpress("F:\School\FIT\Thesis\Scaled Simulations\Reference_13_01-Pressure.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Aug-2023 12:45:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["time", "p_1", "Var3", "Var4", "Var5"];
opts.SelectedVariableNames = ["time", "p_1"];
opts.VariableTypes = ["double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var4", "Var5"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "time", "TrimNonNumeric", true);
opts = setvaropts(opts, "time", "ThousandsSeparator", ",");

% Import the data
Reference1301Pressure = readtable(filename, opts);

end