function CoolTermCapture20230906133503 = importfile2(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  COOLTERMCAPTURE20230906133503 = IMPORTFILE2(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  COOLTERMCAPTURE20230906133503 = IMPORTFILE2(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  CoolTermCapture20230906133503 = importfile2("C:\Users\arewy\OneDrive\Desktop\CoolTerm Capture 2023-09-06 13-35-03.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Sep-2023 12:42:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Strain", "Var3", "Var4"];
opts.SelectedVariableNames = "Strain";
opts.VariableTypes = ["string", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
CoolTermCapture20230906133503 = readtable(filename, opts);

end