function ProbeFluidVelocity = importdat3(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  PROBEFLUIDVELOCITY = IMPORTFILE3(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PROBEFLUIDVELOCITY = IMPORTDAT3(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ProbeFluidVelocity = importdat3("D:\Thesis\Scaled Simulations\Morison Coefficients\13\Probe Fluid Velocity.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Sep-2023 17:03:42

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["time", "v_1", "Var3", "Var4", "Var5"];
opts.SelectedVariableNames = ["time", "v_1"];
opts.VariableTypes = ["double", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var4", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var4", "Var5"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "time", "TrimNonNumeric", true);
opts = setvaropts(opts, "time", "ThousandsSeparator", ",");

% Import the data
ProbeFluidVelocity = readtable(filename, opts);

end